<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Inherite" Id="{57f9dae1-c0b4-4b5b-b6b6-fa25af668858}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Inherite EXTENDS FB_Conveyor
VAR_INPUT
END_VAR
VAR_OUTPUT
    nBasisCounter: BYTE;
END_VAR
VAR
    fbBasis: FB_Conveyor;
	nLifesign2: WORD;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbBasis();

nBasisCounter := SUPER^.bLifesign;

nLifesign2 := nLifesign2 + 1;

]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>